### ISSUE TITLE
Compatability with Plasma 6

### ISSUE THREAD

**Issue by educanorama** [Davide-sd/ip_address#20]
I am a long-time user of Public IP address, and appreciate your work on it! 

If you ever update the widget to work with Plasma 6, you can be sure that at least one user will again add it gratefully to the panel.  For now, however, I have to do without it.  My distro just updated to Plasma 6, and the widget is reported as incompatible.

**Comment by Davide-sd** [comment]
Hello @educanorama ,

Thanks for letting me know about the release of Plasma 6. I hope the porting to Plasma 6 is easy, because right now I don't really have much free time. Hopefully I'll give it a try this weekend.

In the meantime, if someone would like to attempt a porting I happily accept a Pull Request.

**Comment by educanorama** [comment]
Thanks for the reply, Davide.  I'll wish you the best in your porting efforts!

**Comment by Davide-sd** [comment]
Ok, porting complete. You can find the package at [this page](https://www.pling.com/p/2140275/). Thank you again for letting me know about Plasma 6 :)

**Comment by educanorama** [comment]
Thank **_you_** for the update, Davide!  My favorite plasmoid has returned.
